#!/usr/bin/env bash
#
# One-step installer.
#
#   ./install.sh
#
# Everything lives under $HOME, so a SteamOS update cannot remove it and no
# root access is needed at any point.
#
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APP_NAME="proton-vcredist"
INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/$APP_NAME"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/$APP_NAME"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT="$UNIT_DIR/$APP_NAME.service"

say()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m==>\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -ne 0 ] || die "Run this as your normal user, not as root."
command -v python3 >/dev/null || die "python3 not found."
[ -d "$SOURCE_DIR/pvc" ] || die "cannot find the pvc/ package next to this script."

say "Installing $APP_NAME to $INSTALL_DIR"
rm -rf "$INSTALL_DIR"
install -d "$INSTALL_DIR" "$BIN_DIR" "$UNIT_DIR"
cp -r "$SOURCE_DIR/pvc" "$INSTALL_DIR/"
find "$INSTALL_DIR" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by $APP_NAME install.sh
PYTHONPATH="$INSTALL_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONPATH
exec python3 -m pvc.main "\$@"
EOF
chmod +x "$LAUNCHER"

# SteamOS does not put ~/.local/bin on PATH, so the bare command name would be
# "command not found" even though the install worked.
CMD="$LAUNCHER"
case ":$PATH:" in
    *":$BIN_DIR:"*)
        CMD="$APP_NAME"
        ;;
    *)
        MARKER="# added by $APP_NAME"
        if ! { [ -f "$HOME/.bashrc" ] && grep -qF "$MARKER" "$HOME/.bashrc"; } 2>/dev/null; then
            printf '\n%s\nexport PATH="$HOME/.local/bin:$PATH"\n' "$MARKER" >> "$HOME/.bashrc"
        fi
        warn "$BIN_DIR is not on your PATH; added it to ~/.bashrc."
        warn "It applies to NEW terminals. Use the full path in this one."
        ;;
esac

# Runs once per login, when no game can be mid-launch. New prefixes created
# while you were playing get picked up next time you log in; prefixes that are
# already done are skipped by their marker file, so this is nearly free.
say "Installing the login service"
cat > "$UNIT" <<EOF
[Unit]
Description=Install the Visual C++ runtime into new Proton prefixes
After=default.target

[Service]
Type=oneshot
ExecStart=$LAUNCHER --all --x86 --quiet
# One slow prefix must not hold up the session.
TimeoutStartSec=1800

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable "$APP_NAME.service" >/dev/null

# A clickable launcher, because on a handheld the on-screen keyboard belongs to
# Steam: if a fix required closing Steam and typing a command, it would be
# unusable exactly when you need it.
say "Adding a desktop launcher"
DESKTOP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
install -d "$DESKTOP_DIR"
cat > "$DESKTOP_DIR/$APP_NAME.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Fix Games: Visual C++ Runtime
Comment=Install the Visual C++ 2015-2022 runtime into every Proton prefix
Exec=$LAUNCHER --all --x86 --notify --pause
Icon=applications-games
Terminal=true
Categories=Game;Utility;
Keywords=proton;wine;vcredist;visual;runtime;
EOF
chmod +x "$DESKTOP_DIR/$APP_NAME.desktop"
update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true

cat <<EOF

$(say "Installed.")

  NO KEYBOARD NEEDED. Two ways to run it without typing anything:

    1. Just reboot. It runs automatically at every login.
    2. Application menu -> "Fix Games: Visual C++ Runtime" (click it).

  Steam can stay open. Prefixes with a game actually running in them are
  detected and skipped, then picked up the next time.

  From a terminal, if you have one:
    See your prefixes ..  $CMD --list
    Fix one game .......  $CMD --appid <APPID>
    Fix everything .....  $CMD --all --x86

  Uninstall ............  $SOURCE_DIR/uninstall.sh
EOF
