#!/usr/bin/env bash
#
# One-step installer.
#
#   ./install.sh
#
# Everything lives under $HOME, so a SteamOS update cannot remove it and no
# root access is needed at any point.
#
set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

APP_NAME="proton-vcredist"
INSTALL_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/$APP_NAME"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/$APP_NAME"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT="$UNIT_DIR/$APP_NAME.service"

say()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m==>\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -ne 0 ] || die "Run this as your normal user, not as root."
command -v python3 >/dev/null || die "python3 not found."
[ -d "$SOURCE_DIR/pvc" ] || die "cannot find the pvc/ package next to this script."

say "Installing $APP_NAME to $INSTALL_DIR"
rm -rf "$INSTALL_DIR"
install -d "$INSTALL_DIR" "$BIN_DIR" "$UNIT_DIR"
cp -r "$SOURCE_DIR/pvc" "$INSTALL_DIR/"
find "$INSTALL_DIR" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true

cat > "$LAUNCHER" <<EOF
#!/bin/sh
# Generated by $APP_NAME install.sh
PYTHONPATH="$INSTALL_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONPATH
exec python3 -m pvc.main "\$@"
EOF
chmod +x "$LAUNCHER"

# SteamOS does not put ~/.local/bin on PATH, so the bare command name would be
# "command not found" even though the install worked.
CMD="$LAUNCHER"
case ":$PATH:" in
    *":$BIN_DIR:"*)
        CMD="$APP_NAME"
        ;;
    *)
        MARKER="# added by $APP_NAME"
        if ! { [ -f "$HOME/.bashrc" ] && grep -qF "$MARKER" "$HOME/.bashrc"; } 2>/dev/null; then
            printf '\n%s\nexport PATH="$HOME/.local/bin:$PATH"\n' "$MARKER" >> "$HOME/.bashrc"
        fi
        warn "$BIN_DIR is not on your PATH; added it to ~/.bashrc."
        warn "It applies to NEW terminals. Use the full path in this one."
        ;;
esac

# Runs once per login, when no game can be mid-launch. New prefixes created
# while you were playing get picked up next time you log in; prefixes that are
# already done are skipped by their marker file, so this is nearly free.
say "Installing the login service"
cat > "$UNIT" <<EOF
[Unit]
Description=Install the Visual C++ runtime into new Proton prefixes
After=default.target

[Service]
Type=oneshot
ExecStart=$LAUNCHER --all --quiet
# One slow prefix must not hold up the session.
TimeoutStartSec=1800

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable "$APP_NAME.service" >/dev/null

cat <<EOF

$(say "Installed.")

  See your prefixes ....  $CMD --list
  Fix one game .........  $CMD --appid <APPID>
  Fix everything .......  $CMD --all
  Also 32-bit ..........  add --x86

  New prefixes are handled automatically at each login.

  Close Steam before running --all: the installer writes into prefixes, and
  a game running in one at the same time can confuse it.

  Uninstall ............  $SOURCE_DIR/uninstall.sh
EOF
